/** リストを表示するための仮データ */
export const mocList = [
  {
    itemCode: 'XXXX-000000',
    category: '備品',
    itemName: '厚底ブーツ',
    stock: 1,
    lastOrder: '2010年10月10日',
  },
  {
    itemCode: 'XXXX-000001',
    category: 'おやつ',
    itemName: '京都限定・宇治抹茶ホイップあずき',
    stock: 20,
    lastOrder: '2011年1月1日',
  },
  {
    itemCode: 'XXXX-000002',
    category: 'ご当地ナンバー',
    itemName: '神戸',
    stock: 20,
    lastOrder: '2012年2月2日',
  },
  {
    itemCode: 'XXXX-000003',
    category: 'ドリンク',
    itemName: 'ソルティライチ',
    stock: 4000,
    lastOrder: '2013年3月3日',
  },
  {
    itemCode: 'XXXX-000004',
    category: 'アルバム',
    itemName: 'Rising Sun [通常盤]',
    stock: 0,
    lastOrder: '2014年4月4日',
  },
  {
    itemCode: 'XXXX-000005',
    category: 'アルバム',
    itemName: 'More ! More ! ! More ! ! !',
    stock: 0,
    lastOrder: '2015年5月5日',
  },
  {
    itemCode: 'XXXX-000006',
    category: '締めつけ工具',
    itemName: 'マイナスドライバー',
    stock: 20,
    lastOrder: '2016年6月6日',
  },
  {
    itemCode: 'XXXX-000007',
    category: '装備品',
    itemName: '盾',
    stock: 200,
    lastOrder: '2017年7月7日',
  },
  {
    itemCode: 'XXXX-000008',
    category: '歌詞',
    itemName: 'たたかいつかれて おやすみグッナイ まぶたを閉じれば よみがえる',
    stock: 1,
    lastOrder: '2018年8月8日',
  },
  {
    itemCode: 'XXXX-000009',
    category: '歌詞',
    itemName: 'ユメは いつか ホントになるって だれかが歌って いたけど',
    stock: 1,
    lastOrder: '2019年9月9日',
  },
];
